import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-4 md:p-32 bg-purple-400">
          <div className="w-full bg-gray-50 p-10 h-full rounded-md shadow-lg space-y-5">
            <div className="text-center p-5">
              <Link className="text-4xl font-bold text-purple-950" href="/">
                Personal Expense Tracker
              </Link>
            </div>
            <Toaster
              position="top-center"
              reverseOrder={false}
            />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
